version: '3.1'
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_pasquali_api_development
    volumes:
      - ./db_data:/var/lib/mysql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./test_pasquali_api:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  front:
    build:
      context: .
      dockerfile: DockerfileFront
    ports:
      - "4200:4200"
    command: ng serve --host 0.0.0.0
    volumes:
      - ./test-pasquali-front:/myapp
