version: '3.1'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_pasquali_development
    volumes:
      - ./test_pasquali_api/tmp/db:/var/lib/mysql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./test_pasquali_api:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  front:
    image: node
    ports:
      - "4200:4200"
